---
apiVersion: v1
kind: Service
metadata:
  name: certificate-export
  labels:
    app: certificate-export
spec:
  selector:
    app: certificate-export
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP